"""books and facebook table created

Revision ID: 5ad1e021d098
Revises: 
Create Date: 2020-04-15 15:19:31.385912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ad1e021d098'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('type_of_book', sa.String(length=64), nullable=True),
    sa.Column('synopsis', sa.String(length=512), nullable=True),
    sa.Column('publisher', sa.String(length=128), nullable=True),
    sa.Column('publication_date', sa.DateTime(), nullable=True),
    sa.Column('languge', sa.String(length=64), nullable=True),
    sa.Column('isbn', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_name'), 'books', ['name'], unique=False)
    op.create_table('facebook_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(length=128), nullable=True),
    sa.Column('body', sa.String(length=1024), nullable=True),
    sa.Column('publication_date', sa.DateTime(), nullable=True),
    sa.Column('post_link', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('facebook_posts')
    op.drop_index(op.f('ix_books_name'), table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
