"""corrected language spelling

Revision ID: a5bb67a94731
Revises: 5ad1e021d098
Create Date: 2020-04-17 15:59:29.038443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5bb67a94731'
down_revision = '5ad1e021d098'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('language', sa.String(length=64), nullable=True))
    op.drop_column('books', 'languge')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('languge', sa.VARCHAR(length=64), nullable=True))
    op.drop_column('books', 'language')
    # ### end Alembic commands ###
